/* DO NOT TOUCH!!!! This file is autogenerated by make, and should not be
 * modified directly. */
#ifndef PUBFUNCS_H_INCLUDED
#define PUBFUNCS_H_INCLUDED

#include "shared.h"

extern void initializeGenerator();
extern int *generateUnboundedNumberOfIntegers(int numberOfIntegers);
extern int *generateUpperBoundedNumberOfIntegers(int numberOfIntegers, int bound);
extern int *generateLowerBoundedNumberOfIntegers(int numberOfIntegers, int bound);
extern int *generateBoundedNumberOfIntegers(int numberOfIntegers, int lowerBound, int upperBound);
extern int *createEmptyList(int numberOfIntegers);
extern void printIntegerList(int *list, int length);
extern int validateStringIsInt(char *);
extern int validateStringIsFloat(char *);
extern void throw (void (*)(void *), ...);
extern void notImplementedError();
extern void missingArgumentError(char *);
extern void invalidArgumentInputError(char *);
extern void invalidDataTypeFlagError(byte);
extern void help();

#endif
